name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  token:
    required: true
    description: "Github token"
  packageType:
    required: true
  organization:
    required: true
  jfrogURL:
    required: true
  jfrog-username:
    required: true
  jfrog-password:
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
